# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-07-12 16:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 12, 16, 30, 6, 93000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
