# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-07-12 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listpage', '0002_auto_20180712_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='data',
            field=models.TextField(default=datetime.datetime(2018, 7, 12, 16, 37, 14, 511000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
